name: Hello World

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name:  Test Phase
        run: echo "Runnning Test Cases"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to App
        run: echo "Deploying the app"
  
